<a href="https://colab.research.google.com/github/sujithm21/Potato_Plant_Disease_Detection/blob/main/Potato_leaf_disease_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from IPython.display import HTML

In [8]:
IMAGE_SIZE = 256
CHANNELS = 3

In [9]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True
)
train_generator = train_datagen.flow_from_directory(
        '/content/sample_data/Dataset',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse",
#         save_to_dir="C:\\Code\\potato-disease-classification\\training\\AugmentedImages"
)

Found 2121 images belonging to 4 classes.


In [10]:
train_generator.class_indices

{'.ipynb_checkpoints': 0,
 'Potato___Early_blight': 1,
 'Potato___Late_blight': 2,
 'Potato___healthy': 3}

In [11]:
class_names = list(train_generator.class_indices.keys())
class_names

['.ipynb_checkpoints',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy']

In [12]:
count=0
for image_batch, label_batch in train_generator:
#     print(label_batch)
    print(image_batch[0])
    break

[[[0.689221   0.6813779  0.7362799 ]
  [0.6875072  0.6796641  0.73456603]
  [0.68579346 0.6779503  0.7328523 ]
  ...
  [0.5123946  0.5045515  0.55553186]
  [0.49536902 0.48752588 0.53850627]
  [0.45391276 0.44606963 0.49705002]]

 [[0.70780504 0.6999619  0.7548639 ]
  [0.70666254 0.6988194  0.75372136]
  [0.70552003 0.6976769  0.75257885]
  ...
  [0.514394   0.50655085 0.55753124]
  [0.4887995  0.48095638 0.5319368 ]
  [0.45676908 0.44892594 0.49990633]]

 [[0.6967083  0.6888652  0.74376714]
  [0.6987077  0.69086456 0.7457665 ]
  [0.70070714 0.692864   0.74776596]
  ...
  [0.5163934  0.5085503  0.5595307 ]
  [0.48223    0.47438687 0.52536726]
  [0.4596254  0.45178226 0.5027627 ]]

 ...

 [[0.7508565  0.7508565  0.79791534]
  [0.7889601  0.7889601  0.8360189 ]
  [0.76510996 0.76510996 0.8121688 ]
  ...
  [0.56616163 0.5504753  0.6053773 ]
  [0.56758976 0.5519035  0.60680544]
  [0.56901795 0.5533317  0.60823363]]

 [[0.7582829  0.7582829  0.8053417 ]
  [0.78667504 0.78667504 0.83373386]


In [15]:
validation_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)
validation_generator = validation_datagen.flow_from_directory(
        '/content/sample_data/Dataset',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 2121 images belonging to 4 classes.


In [16]:
test_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=10,
        horizontal_flip=True)

test_generator = test_datagen.flow_from_directory(
        '/content/sample_data/Dataset',
        target_size=(IMAGE_SIZE,IMAGE_SIZE),
        batch_size=32,
        class_mode="sparse"
)

Found 2121 images belonging to 4 classes.


In [17]:
for image_batch, label_batch in test_generator:
    print(image_batch[0])
    break

[[[0.5803922  0.5529412  0.6156863 ]
  [0.5803922  0.5529412  0.6156863 ]
  [0.5803922  0.5529412  0.6156863 ]
  ...
  [0.45882356 0.427451   0.4784314 ]
  [0.46791092 0.43653837 0.48751876]
  [0.49141645 0.4600439  0.5110243 ]]

 [[0.56727535 0.5398243  0.60256946]
  [0.568853   0.54140204 0.60414714]
  [0.57043064 0.54297966 0.60572475]
  ...
  [0.45882356 0.427451   0.4784314 ]
  [0.47011966 0.4387471  0.48972753]
  [0.49267858 0.46130604 0.5122865 ]]

 [[0.55556303 0.52811205 0.59085715]
  [0.55619407 0.5287431  0.5914882 ]
  [0.55682516 0.5293742  0.5921193 ]
  ...
  [0.45882356 0.427451   0.4784314 ]
  [0.4723284  0.44095585 0.49193624]
  [0.49394074 0.4625682  0.51354855]]

 ...

 [[0.6451423  0.61769134 0.6451423 ]
  [0.65303576 0.6255848  0.65303576]
  [0.6627828  0.6353318  0.6627828 ]
  ...
  [0.53930974 0.48832935 0.5157803 ]
  [0.5408874  0.48990703 0.517358  ]
  [0.5424651  0.4914847  0.5189356 ]]

 [[0.6454578  0.6180068  0.6454578 ]
  [0.6539824  0.6265314  0.6539824 ]


In [18]:
input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
n_classes = 3

model = models.Sequential([
    layers.InputLayer(input_shape=input_shape),
    layers.Conv2D(32, kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64,  kernel_size = (3,3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(n_classes, activation='softmax'),
])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 127, 127, 32)      0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 62, 62, 64)        0         
 g2D)                                                            
                                                                 
 conv2d_2 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_2 (MaxPoolin  (None, 30, 30, 64)        0

In [20]:
model.compile(
    optimizer='adam',
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=['accuracy']
)